### ISSUE TITLE
Support for CWL 1.1

### ISSUE THREAD

**Issue by KerstenBreuer** [common-workflow-language/cwl-utils#10]
Is support for CWL v1.1 coming soon?

I would like to use this packages in [CWLab](https://github.com/CompEpigen/CWLab) but I need support for the latest CWL version.

**Comment by mr-c** [comment]
@KerstenBreuer There is a v1.1 parser in https://github.com/common-workflow-language/cwl-utils/pull/5

I can merge that and move the notes to an issue, and then make a release, if you need that.

**Comment by KerstenBreuer** [comment]
Hi @mr-c,

That would be great. Then I could replace the CWL parsing currently done with cwltool by this package.

Thanks a lot

**Comment by mr-c** [comment]
https://github.com/common-workflow-language/cwl-utils/releases/tag/0.3

https://pypi.org/project/cwl-utils/0.3/

@KerstenBreuer Enjoy!
