### ISSUE TITLE
can't open file 'docker_extract.py'

### ISSUE THREAD

**Issue by johnbradley** [common-workflow-language/cwl-utils#11]
When running `python docker_extract.py` I get the following error:
```
python: can't open file 'docker_extract.py': [Errno 2] No such file or directory
```
after installing version `0.1` from pypi.

I think this has already been fixed by https://github.com/common-workflow-language/cwl-utils/commit/c2b4972724a810962a871b413c8840d1c6e9bb8b.
If I install directly from github master branch I can run `docker_extract.py` without error.

I think this problem could be resolved by releasing a new version that includes the above commit.

Thanks.

**Comment by mr-c** [comment]
@johnbradley Happily, thanks! https://github.com/common-workflow-language/cwl-utils/releases/tag/0.2

**Comment by mr-c** [comment]
and https://pypi.org/project/cwl-utils/0.2/
