### ISSUE TITLE
switching to all Apache 2.0 licensing

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwl-utils#155]
Can I get a confirmation for
- [x] @mb1069
- [x] @gijzelaerr
- [x] @khillion 
- [x] @tom-tan
- [x] @GlassOfWhiskey
- [x] @altairwei
- [x] @manabuishii
- [x] @kinow

To relicense the following files under Apache 2.0?

- `cwl_utils/docker_extract.py` (previously named `cwl_utils/docker-extract.py`, `docker_cache_pull/docker-extract.py`)
- `cwl_utils/image_puller.py`
- `cwl_utils/cite_extract.py` (previously named `cwl_utils/cite-extract.py`, `docker_cache_pull/cite-extract.py`)
- `cwl_utils/graph_split.py`

A comment on this PR affirming the license change is all that is needed; thanks!

**Comment by gijzelaerr** [comment]
go for it

**Comment by kinow** [comment]
+1 thanks!

**Comment by tom-tan** [comment]
+1!

**Comment by altairwei** [comment]
all right

**Comment by GlassOfWhiskey** [comment]
No problem for me

Il mer 31 ago 2022, 12:25 Altair Wei ***@***.***> ha scritto:

**Comment by khillion** [comment]
All good for me too! Thanks

**Comment by mb1069** [comment]
Go for it!

**Comment by manabuishii** [comment]
No problem !!
+1
