### ISSUE TITLE
ImportError: cannot import name 'Fetcher' from 'schema_salad.ref_resolver'

### ISSUE THREAD

**Issue by ryantanaka** [common-workflow-language/cwl-utils#20]
I am running into this ImportError when running: 
```>>> import cwl_utils.parser_v1_1 as cwl```

```
Python 3.7.7 (default, Mar 10 2020, 15:43:03)
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cwl_utils.parser_v1_1 as cwl
INFO:rdflib:RDFLib Version: 4.2.2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ryantanaka/ISI/venv/lib/python3.7/site-packages/cwl_utils/parser_v1_1.py", line 13, in <module>
    from schema_salad.ref_resolver import Fetcher
ImportError: cannot import name 'Fetcher' from 'schema_salad.ref_resolver' (/Users/ryantanaka/ISI/venv/lib/python3.7/site-packages/schema_salad/r$f_resolver.py)
```

I have `schema-salad` version **7.0.20200612160654** and observed the above error with `cwl-utils` versions **0.3** and **0.4**.

Are you guy seeing the same behavior?

thank you

**Comment by mr-c** [comment]
Hello @ryantanaka ; my apologies for this error. This project hadn't put restrictions on the schema salad version and we just released a breaking change. I've opened #21 to fix this.
