### ISSUE TITLE
Slow document loading starting with 0.3

### ISSUE THREAD

**Issue by ksebby** [common-workflow-language/cwl-utils#34]
Hi. Not sure if this should be here or in the schema-salad repo. There were significant changes in the code generated between cwl-utils versions 0.2 and 0.3 which cause cwl documents loaded with `cwl_utils.parser_v1_0.load_document` to load very slowly. The culprit seem to be many calls to `copy.deepcopy`; specifically `loadingOptions = copy.deepcopy(loadingOptions)` in the fromDoc class methods. This is problem arose for me because I use load_document in tests and the times really add up when testing a lot of files.  For larger files such as https://github.com/truwl/capanno/blob/master/cwl-tools/STAR/2.5/STAR_alignReads/STAR-alignReads.cwl  take ~0.5 sec to load with version 0.2 and 17 seconds to load in 0.3-0.7.  Loading the above file with `cwl_utils.parser_v1_0.load_document` makes almost 9 million calls to `copy.deepcopy()`mostly from `_RecordLoader.load()`. Is there a way to reduce all of these calls? Thanks.

**Comment by mr-c** [comment]
Hey @ksebby 


That `deepcopy` call dates back to July 2019 which is before the cwl-utils version 0.2 release but it is true that it didn't propagate to cwl-utils until version 0.3

https://github.com/common-workflow-language/schema_salad/pull/263/commits/7cd81f0fb4a5dac8b4d149bed6796cfb3f9a2e12#diff-af73c7b2af6d389649208b4de29a2687R172

https://github.com/common-workflow-language/cwl-utils/compare/0.2...0.3#diff-949be88024058c77618e213f9a521479R9249

The `original_doc` value was added to support generating good error messages after parsing that relate to the original line numbers https://github.com/common-workflow-language/cwl-utils/blob/0f1a446c89523d4305d6b4ca663a9a3c9924264b/cwl_utils/etools_to_clt.py#L332

If you find that removing the `loadingOptions = copy.deepcopy(loadingOptions)` line means that everything still works then I would accept such a PR to the schema_salad `schema_salad/python_codegen.py` file.

Thank you for tracking this down!

**Comment by ksebby** [comment]
Thanks @mr-c. I'll give that a try and let you know how it goes!
