### ISSUE TITLE
Question: Convert v1.0 to v1.2

### ISSUE THREAD

**Issue by BJWiley233** [common-workflow-language/cwl-utils#88]
Hi,

I was referred to the repo by DNAnexus that there may be tools here to convert my CWL from v1.0 to v1.2, however I don't see any hard documentation for a conversion here, only the parsers on the markdown.  Is there documentation for converting CWL versions?

Brian

**Comment by BJWiley233** [comment]
Found the normalizer script.  Ran it and got error below for a custom type entry:

```
`type` field is not valid because: Expected one of ('record',) 
invalid field
`items`, expected one of: `fields`,
`type`, `label`, `doc`, `name`,
`inputBinding`
```

Here is the input:
```
custom_annotations:
        type:
            - "null"
            - type: array
              items: ../types/vep_custom_annotation.yml#vep_custom_annotation
              label: "custom type, check types directory for input format"
              inputBinding:
                  valueFrom: |
                       ${
                           return [self.annotation.check_existing ? '--check_existing' : '',
                             '--custom',
                             [self.annotation.file.path,
                             self.annotation.name,
                             self.annotation.data_format,
                             self.method,
                             self.force_report_coordinates ? 1 : 0,
                             self.annotation.vcf_fields ? self.annotation.vcf_fields : ''
                             ].filter(String).join(',')
                           ].filter(String)
                       }
                  position: 6
```

**Comment by tetron** [comment]
You want https://github.com/common-workflow-language/cwl-upgrader

**Comment by BJWiley233** [comment]
ok cool, I will try, thanks

**Comment by mr-c** [comment]
The normalizer script calls cwl-upgrader, so I'll take a look.

**Comment by BJWiley233** [comment]
cwl-upgrader worked on that tool and type!  quick question, is there a plan add an indentation argument to cwl-upgrader with respect to how many spaces ruamel will indent with `yml.indent`?

**Comment by mr-c** [comment]
> Should I make an enhancement request for this?)

That is an error, so please open a new issue for that, thanks

**Comment by mr-c** [comment]
> `--dir` just puts it all in the same folder. (Should I make an enhancement request for this?)

Sure, but that won't be a high priority item for me
